CC=gcc
CFLAGS=-g
BIN=miniftpd
OBJS=miniftp.o sysutil.o session.o ftpproto.o privparent.o
LIBS=

$(BIN):$(OBJS)
	$(CC) $(CFLAGS) $^ -o $@ $(LIBS)
%.o:%.c
	$(CC) $(CFLAGS) -c $< -o $@

.PHONY:clean
clean:
	rm -f *.o $(BIN)
